language: node_js
before_install:
    - openssl aes-256-cbc -k "$super_secret_password" -in se234.pem.enc -out se234.pem -d
    - sudo chmod 400 se234.pem
install: true
script: true
after_success:
    - ls -l
    - scp -i "se234.pem" -r html/* ubuntu@172.31.31.232:/var/www/html/
addons:
  ssh_known_hosts:
       - 172.31.31.232
